tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "jesseduffield/lazygit"
# B2 Cloud Storage Command-Line Tools
brew "b2-tools"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Console Matrix
brew "cmatrix"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Modern, maintained replacement for ls
brew "eza"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Command-line fuzzy finder written in Go
brew "fzf"
# Distributed revision control system
brew "git"
# Lazier way to manage everything docker
brew "lazydocker"
# Mac App Store command-line interface
brew "mas"
# Terminal-based visual file manager
brew "midnight-commander"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Platform built on V8 to build network applications
brew "node"
# Pretty system information tool written in POSIX sh
brew "pfetch"
# Theme for zsh
brew "powerlevel10k"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Command-line interface for https://speedtest.net bandwidth tests
brew "speedtest-cli"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Vi 'workalike' with many additional features
brew "vim"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# A simple terminal UI for git commands, written in Go
brew "jesseduffield/lazygit/lazygit"
# GPU-accelerated terminal emulator
cask "alacritty"
# Desktop password and login vault
cask "bitwarden"
# OpenAI's official ChatGPT desktop app
cask "chatgpt"
# UI for creating Windows installer ISO from UUPDump
cask "crystalfetch"
# Voice and text chat software
cask "discord"
# App to build and share containerised applications and microservices
cask "docker"
# Typeface made for developers
cask "font-jetbrains-mono"
# Developer targeted fonts with a high number of glyphs
cask "font-meslo-lg-nerd-font"
# Web browser
cask "google-chrome"
# Wallet desktop application to maintain multiple cryptocurrencies
cask "ledger-live"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Office suite
cask "microsoft-office"
# Remote desktop client
cask "microsoft-remote-desktop"
# Sandbox construction video game
cask "minecraft"
# Peer to peer Bitorrent client
cask "qbittorrent"
# Music streaming service
cask "spotify"
# Video game digital distribution service
cask "steam"
# Messaging app with a focus on speed and security
cask "telegram"
# Virtual machines UI using QEMU
cask "utm"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
mas "DaVinci Resolve", id: 571213070
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "WireGuard", id: 1451685025
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
